### ISSUE TITLE
Menubar is missing in linux QT

### ISSUE THREAD

**Issue by nanocoinorg** [rat4/blackcoin#44]
I issued a pull request to fix the menubar for linux QT.

**Comment by rat4** [comment]
I don't experience any issues with the menu on linux. What's your
distribution and desktop environment?

**Comment by nanocoinorg** [comment]
Ubuntu 14.04 Desktop, the entire file menu is missing unless I add the change listed in the pull request. 

Let me know if I can provide additional information.

**Comment by crispybear** [comment]
Desktop environment? I am using xfce and has no problem with the menu bar.

**Comment by nanocoinorg** [comment]
Yes vanillia desktop install, I tested it on a few different installs to confirm. You can try it yourself, it is a popular version of linux so its worth confirming it works.

**Comment by crispybear** [comment]
I have tested it on a freshly installed ubuntu in a vm and this bug is indeed existed.

This issue only present when `appmenu-qt5` package is installed. So I am not sure if it is a bug in Blackcoin itself, or in appmenu-qt5.

Also, I noted that the menu is not missing after applying your pull request. However, if I minimize the window to tray (by clicking the tray icon, not minimize to the taskbar), and restore it again, the menu is gone again.

**Comment by crispybear** [comment]
Another issue i found is the tray icon does not goes into tray on a vanilla ubuntu install. Instead, the icon stay at the top left cornet. http://www.zimagez.com/zimage/screenshot-220315-214958.php

**Comment by rat4** [comment]
The menu issue looks like a bug in appmenu-qt5/unity, but we can workaround it quite easy. The tray seems to be bug in qt5 https://bugreports.qt.io/browse/QTBUG-31762 no idea how we could workaround that.
